fun main() {
    println("student Enrollment no is: ")
    val studentEnrollmentno = readlnOrNull()
    println("Student Name: ")
    val StudentName = readlnOrNull()
    println("student branch is: ")
    val studentbranch = readlnOrNull()
    println("student class is: ")
    val studentclass = readlnOrNull()
    println("student batch is: ")
    val studentbatch = readlnOrNull()
    println("student College name is: ")
    val studentcollegename = readlnOrNull()

    println("Enrollment number: $studentEnrollmentno")
    println("Name: $StudentName")
    println("student branch is: $studentbranch")
    println("student class is: $studentclass")
    println("student batch is: $studentbatch")
    println("student college name : $studentcollegename")
}